name: "Get deployment information"
description: "Get the information required to build and deploy an Octue service."
author: "cortadocodes"
#branding:
#  icon: git-pull-request
#  color: green
inputs:
  gcp_project_name:
    description: "The name of the Google Cloud project being deployed to."
    required: true
  gcp_project_number:
    description: "The number of the Google Cloud project being deployed to."
    required: true
  gcp_region:
    description: "The Google Cloud region being deployed to."
    required: true
  gcp_resource_affix:
    description: ""
    required: true
  gcp_service_name:
    description: "The name of the service being deployed."
    required: true
  gcp_environment:
    description: ""
    required: false
    default: main

outputs:
  branch_tag_kebab:
    description: "The tag or branch name in kebab case."
  branch_tag_screaming:
    description: "The tag or branch name in screaming snake case."
  image_latest_artefact:
    description: "The artefact URI for the latest docker image."
  image_latest_tag:
    description: "The tag of the latest docker image."
  image_version_artefact:
    description:  "The artefact URI for the docker image for the version to deploy."
  image_version_tag:
    description: "The tag of the docker image for the version."
  short_sha:
    description: "The short SHA of the HEAD commit being deployed."
  version_slug:
    description: "The slugified version."
  gcp_environment:
    description: ""
  gcp_project_name:
    description: ""
  gcp_project_number:
    description: ""
  gcp_region:
    description: ""
  gcp_resource_affix:
    description: ""
  gcp_service:
    description: ""
  version:
    description: "The version being deployed."

runs:
  using: "docker"
  image: "docker://octue/get-deployment-info:0.1.0"
  args:
    - ${{ inputs.gcp_project_name }}
    - ${{ inputs.gcp_project_number }}
    - ${{ inputs.gcp_region }}
    - ${{ inputs.gcp_resource_affix }}
    - ${{ inputs.gcp_service_name }}
    - ${{ inputs.gcp_environment }}
